#!/usr/bin/env python3
"""Render an additive, pre-conntrack guard for the two XDP service nodes."""
import sys

PROFILES = {
    'ohz': ('"eth0", "eth1", "eth2"', '85.208.114.51, 85.208.114.52, 85.208.114.54',
            '2a0e:97c0:c40::51, 2a0e:97c0:c40::52, 2a0e:97c0:c40::54'),
    'oci': ('"enp0s6"', '10.0.0.86, 10.0.0.81',
            '2603:c027:8703:d400::10, 2603:c027:8703:d400::40'),
    'test': ('"guard-in"', '198.18.0.1', 'fd00::1'),
}

def render(profile):
    interfaces, v4, v6 = PROFILES[profile]
    lines = ['# Generated by security/generate-ddos-guard.py; no flush ruleset.',
             '# Rate ceilings are initial operational limits, not guaranteed capacity.',
             'table inet xdp_ddos {']
    for group in ('syn_dns', 'syn_web', 'dns_udp', 'quic_udp'):
        for family, address in ((4, 'ipv4_addr'), (6, 'ipv6_addr')):
            lines += [f'  set {group}{family} {{',
                      f'    type {address} . inet_service',
                      '    flags dynamic,timeout', '    timeout 60s',
                      '    gc-interval 10s', '    size 65535', '  }']
    counters = ('syn_dns_source', 'syn_web_source', 'dns_udp_source', 'quic_udp_source',
                'syn53_global', 'syn853_global', 'synweb_global', 'dnsudp_global',
                'quic_global', 'syn_pass', 'dnsudp_pass', 'quic_pass')
    lines += [f'  counter {name} {{ }}' for name in counters]
    lines += ['  chain prerouting {',
              '    type filter hook prerouting priority raw; policy accept;',
              f'    iifname {{ {interfaces} }} ip daddr {{ {v4} }} jump services',
              f'    iifname {{ {interfaces} }} ip6 daddr {{ {v6} }} jump services', '  }',
              '  chain services {',
              '    tcp dport { 53, 80, 443, 853 } tcp flags & (syn | ack) == syn jump syn_guard',
              '    udp dport 53 jump dns_guard',
              '    udp dport { 443, 853 } jump quic_guard', '  }']
    for chain, rules, global_rules, passed in (
        ('syn_guard', [('tcp', '{ 53, 853 }', 'syn_dns', 20, 100, 'syn_dns_source'),
                       ('tcp', '{ 80, 443 }', 'syn_web', 100, 300, 'syn_web_source')],
         ['tcp dport 53 limit rate over 200/second burst 400 packets counter name syn53_global drop',
          'tcp dport 853 limit rate over 300/second burst 600 packets counter name syn853_global drop',
          'tcp dport { 80, 443 } limit rate over 500/second burst 1000 packets counter name synweb_global drop'], 'syn_pass'),
        ('dns_guard', [('udp', '53', 'dns_udp', 1000, 2000, 'dns_udp_source')],
         ['limit rate over 20000/second burst 40000 packets counter name dnsudp_global drop'], 'dnsudp_pass'),
        ('quic_guard', [('udp', '{ 443, 853 }', 'quic_udp', 5000, 10000, 'quic_udp_source')],
         ['limit rate over 30000/second burst 60000 packets counter name quic_global drop'], 'quic_pass'),
    ):
        lines.append(f'  chain {chain} {{')
        # Global ceiling comes first: bounds set-update work under spoofed-source floods.
        lines += ['    ' + r for r in global_rules]
        for proto, ports, group, rate, burst, counter in rules:
            for family, ip in ((4, 'ip'), (6, 'ip6')):
                lines.append(f'    {proto} dport {ports} update @{group}{family} {{ {ip} saddr . {proto} dport timeout 60s limit rate over {rate}/second burst {burst} packets }} counter name {counter} drop')
        lines += [f'    counter name {passed}', '  }']
    return '\n'.join(lines + ['}', ''])

if __name__ == '__main__':
    print(render(sys.argv[1]), end='')
