bootstrapDns:
- 127.0.0.1:5337
caching:
  minTime: -1m
  maxTime: -1m
  maxItemsCount: 0
certFile: /etc/xdp-tls/fullchain.pem
customDNS:
  customTTL: 1h
  mapping:
    dns.xdp.es: 85.208.114.51,2a0e:97c0:c40::51
    lite.xdp.es: 85.208.114.52,2a0e:97c0:c40::52
ecs:
  forward: false
  useAsClient: true
keyFile: /etc/xdp-tls/privkey.pem
log:
  format: text
  level: warn
  timestamp: true
ports:
  dns:
  - 85.208.114.52:53
  - '[2a0e:97c0:c40::52]:53'
  http: 127.0.0.1:4002
  tls:
  - 85.208.114.52:853
  - '[2a0e:97c0:c40::52]:853'
prometheus:
  enable: true
  path: /metrics
queryLog:
  type: none
upstreams:
  groups:
    default:
    - tcp+udp:127.0.0.1:5337
  strategy: strict
  timeout: 4s
