# /root/xpd-dns/blocky/config-ota.yml
# Blocky Instance for Apple OTA & Update Blocking + Adblock

ports:
  dns: 127.0.0.1:5354
  http: 127.0.0.1:4001

upstreams:
  groups:
    default:
      - tcp+udp:127.0.0.1:5335
  strategy: strict
  timeout: 4s

bootstrapDns:
  - 127.0.0.1:5335
  - 1.1.1.1

caching:
  minTime: 10m
  maxTime: 24h
  prefetching: true
  prefetchExpires: 4h
  prefetchThreshold: 1
  cacheTimeNegative: 15m

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://small.oisd.nl
      - https://urlhaus.abuse.ch/downloads/hostfile/
    apple_ota:
      - /root/xpd-dns/blocky/apple-ota.txt
  clientGroupsBlock:
    default:
      - ads
      - apple_ota
  blockType: zeroIp
  blockTTL: 1m
  loading:
    refreshPeriod: 24h
    downloads:
      timeout: 60s
      cooldown: 10s
      attempts: 3

prometheus:
  enable: true
  path: /metrics

log:
  level: info
  format: text
  timestamp: true
